apiVersion: v2
name: gpu-feature-discovery
type: application
description: A Helm chart for gpu-feature-discovery on Kubernetes
version: "0.6.1"
appVersion: "0.6.1"
kubeVersion: ">= 1.10.0-0"
home: https://github.com/NVIDIA/gpu-feature-discovery
