apiVersion: v2
name: node-feature-discovery
description: |
  Detects hardware features available on each node in a Kubernetes cluster, and advertises
  those features using node labels.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 0.6.0
