apiVersion: v2
name: nvidia-device-plugin
type: application
description: A Helm chart for the nvidia-device-plugin on Kubernetes
version: "0.14.4"
appVersion: "0.14.4"
kubeVersion: ">= 1.10.0-0"
home: https://github.com/NVIDIA/k8s-device-plugin

dependencies:
  - name: node-feature-discovery
    alias: nfd
    version: "0.13.0"
    condition: nfd.enabled,gfd.enabled
    repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
